name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Login
    - name: Login into the docker hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and Push the Docker image
      uses: docker/build-push@v4
      with:
       context: .
       push: true
       tags: ${{secrets.DOCKER_USERNAME}}/web-app:latest
